ko_fi: JackieWaltRyan
liberapay: JackieWaltRyan
patreon: JackieWaltRyan
custom: [ "https://www.privat24.ua/send/g21va", "https://www.paypal.com/donate/?hosted_button_id=G3HY3UDX694WQ", "https://steamcommunity.com/tradeoffer/new/?partner=317077202&token=4c-Gt9Ji" ]
